### ISSUE TITLE
The TTL value is multiplied twice by 1000, resulting into a huge TTL

### ISSUE THREAD

**Issue by kalymero** [lyokato/redlock#21]
Meaning that when passing `40` it results in `40.000` seconds ttl.

First time here: https://github.com/lyokato/redlock/blob/develop/lib/redlock/executor.ex#L45 and second time here: https://github.com/lyokato/redlock/blob/develop/lib/redlock/command.ex#L33

It's also not possible to pass a "40 / 1_000" value since it results into a float value and Redix expect an integer

```[error] Task #PID<0.667.0> started from #PID<0.666.0> terminating
** (Redix.Error) ERR value is not an integer or out of range
    (redix) lib/redix.ex:354: Redix.command/3
    (redlock) lib/redlock/command.ex:33: Redlock.Command.lock/4```

**Comment by kalymero** [comment]
PR: https://github.com/lyokato/redlock/pull/22

**Comment by lyokato** [comment]
merged
